import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SideBar from "@/components/sideBar";
import Footer from "@/components/Footer";
import { Poppins } from 'next/font/google';
import { MovieCacheProvider } from "@/contexts/MovieCacheContext";

const poppins = Poppins({
  subsets: ['latin'],
  weight: '400',
});
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "CineSafe | Stay Safe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${poppins.className} ${geistMono.variable} antialiased bg-gray-900`}
      >
        <MovieCacheProvider>
          <SideBar/>
          {children}
          <Footer />
        </MovieCacheProvider>
      </body>
    </html>
  );
}
